export enum SurveyActions {
  ACCIDENT = 'ACCIDENT',
  COURSE_LINK = 'COURSE_LINK',
  SOCIAL_NETWORKS = 'SOCIAL_NETWORKS',
  SKILLS_FORM = 'SKILLS_FORM',
  SAVE_LOCATION = 'SAVE_LOCATION',
  ASK = 'ASK',
}
