export enum MenuActions {
  GET_LOCATIONS = 'GET_LOCATIONS',
  ACCIDENT = 'ACCIDENT',
  SURVEY = 'SURVEY',
  ASK = 'ASK',
  PRIVATE_CHAT = 'PRIVATE_CHAT',
  COURSE_LINK = 'COURSE_LINK',
  SOCIAL_NETWORKS = 'SOCIAL_NETWORKS',
  SKILLS_FORM = 'SKILLS_FORM',
  SAVE_LOCATION = 'SAVE_LOCATION',
}
